import { Document, Packer, Paragraph, TextRun, HeadingLevel, AlignmentType } from 'docx';

export const handler = async (event, context) => {
  // Handle CORS preflight
  if (event.httpMethod === 'OPTIONS') {
    return {
      statusCode: 200,
      headers: {
        'Access-Control-Allow-Origin': '*',
        'Access-Control-Allow-Methods': 'POST, OPTIONS',
        'Access-Control-Allow-Headers': 'Content-Type',
      },
      body: '',
    };
  }

  try {
    const body = JSON.parse(event.body);
    const plan = body.plan;

    const children = [
      new Paragraph({
        text: 'Course Resource Plan',
        heading: HeadingLevel.HEADING_1,
        alignment: AlignmentType.CENTER,
      }),
      new Paragraph({
        children: [
          new TextRun({
            text: 'Generated by Course Planner',
            italics: true,
          }),
        ],
      }),
      new Paragraph({}), // Empty line
    ];

    for (const item of plan) {
      const chapter = item.chapter;
      const resources = item.resources;

      // Chapter heading
      children.push(
        new Paragraph({
          text: `Chapter ${chapter.number}: ${chapter.title}`,
          heading: HeadingLevel.HEADING_2,
        })
      );

      if (resources && resources.length > 0) {
        children.push(
          new Paragraph({
            text: 'Resources:',
            heading: HeadingLevel.HEADING_3,
          })
        );

        for (const res of resources) {
          const textRuns = [
            new TextRun({
              text: `${res.title} (${res.type})`,
            }),
          ];

          if (res.description) {
            textRuns.push(
              new TextRun({
                text: `: ${res.description}`,
                italics: true,
              })
            );
          }

          children.push(
            new Paragraph({
              children: textRuns,
              bullet: { level: 0 },
            })
          );
        }
      } else {
        children.push(
          new Paragraph({
            text: 'No direct resources found for this chapter.',
            bullet: { level: 0 },
          })
        );
      }

      children.push(new Paragraph({})); // Empty line after each chapter
    }

    const doc = new Document({
      sections: [
        {
          properties: {},
          children: children,
        },
      ],
    });

    const buffer = await Packer.toBuffer(doc);
    const base64 = buffer.toString('base64');

    return {
      statusCode: 200,
      headers: {
        'Content-Type': 'application/json',
        'Access-Control-Allow-Origin': '*',
        'Access-Control-Allow-Methods': 'POST, OPTIONS',
        'Access-Control-Allow-Headers': 'Content-Type',
      },
      body: JSON.stringify({
        fileContent: base64,
        fileName: 'course_plan.docx',
      }),
    };
  } catch (error) {
    console.error('Error generating DOCX:', error);
    return {
      statusCode: 500,
      headers: {
        'Content-Type': 'application/json',
        'Access-Control-Allow-Origin': '*',
      },
      body: JSON.stringify({ error: error.message }),
    };
  }
};
