import json
import base64
from docx import Document
from docx.shared import Inches, Pt
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.oxml.ns import qn

def handler(event, context):
    try:
        body = json.loads(event['body'])
        plan = body['plan']
        
        document = Document()
        
        # Set default font and size
        style = document.styles['Normal']
        font = style.font
        font.name = 'Calibri'
        font.size = Pt(12)

        # Title
        title = document.add_heading('Course Resource Plan', level=1)
        title.alignment = WD_ALIGN_PARAGRAPH.CENTER
        
        document.add_paragraph().add_run('Generated by Course Planner').italic = True
        document.add_paragraph() # Empty line

        for item in plan:
            chapter = item['chapter']
            resources = item['resources']

            # Chapter Heading
            chapter_heading = document.add_heading(f"Chapter {chapter['number']}: {chapter['title']}", level=2)
            chapter_heading.alignment = WD_ALIGN_PARAGRAPH.LEFT

            if resources:
                document.add_heading('Resources:', level=3)
                for res in resources:
                    p = document.add_paragraph(style='List Bullet')
                    p.add_run(f"{res['title']} ({res['type']})")
                    if res.get('description'):
                        p.add_run(f": {res['description']}").italic = True
            else:
                document.add_paragraph('No direct resources found for this chapter.', style='List Bullet')
            document.add_paragraph() # Empty line after each chapter section

        # Save the document to a BytesIO object
        from io import BytesIO
        file_stream = BytesIO()
        document.save(file_stream)
        file_stream.seek(0) # Rewind the stream
        
        # Encode to base64
        encoded_docx = base64.b64encode(file_stream.read()).decode('utf-8')

        return {
            'statusCode': 200,
            'headers': {
                'Content-Type': 'application/json',
                'Access-Control-Allow-Origin': '*', # Adjust for production
                'Access-Control-Allow-Methods': 'POST, OPTIONS',
                'Access-Control-Allow-Headers': 'Content-Type',
            },
            'body': json.dumps({
                'fileContent': encoded_docx,
                'fileName': 'course_plan.docx'
            })
        }
    except Exception as e:
        return {
            'statusCode': 500,
            'headers': {
                'Content-Type': 'application/json',
                'Access-Control-Allow-Origin': '*',
            },
            'body': json.dumps({'error': str(e)})
        }
