# ccc_data_source.py
# This file contains the CCC_DATA list for import by build_db.py

CCC_DATA = [
    # --- Basic Adult Healthcare ---
    ("Basic Adult Healthcare", "Ch 1", "Ch. 01: The NurseThink® Way", "p. 3", "Focuses on critical thinking, the nursing process, and best practice study strategies."),
    ("Basic Adult Healthcare", "Ch 3", "Ch. 04: Unfolding Concepts II", "p. 99", "Strategies for lifestyle choices, risk reduction, and client education."),
    ("Basic Adult Healthcare", "Ch 4", "Ch. 02: Next Gen Clinical Judgment", "p. 81, 83, 85", "Covers cultural, spiritual, and developmental assessments."),
    ("Basic Adult Healthcare", "Ch 5", "Ch. 15: Adaptation", "p. 11, 215", "Addresses stress, coping mechanisms, and physiological immunity/inflammation."),
    ("Basic Adult Healthcare", "Ch 8", "Ch. 17: Cognition", "p. 25, 107", "Management of elder abuse, dementia, and Alzheimer’s disease."),
    ("Basic Adult Healthcare", "Ch 9", "Ch. 14: Comfort", "p. 111–115", "Priorities for acute and chronic pain management."),
    ("Basic Adult Healthcare", "Ch 10", "Ch. 08: Homeostasis", "p. 141–163", "Regulation of acid-base balance, electrolytes, and fluid volume."),
    ("Basic Adult Healthcare", "Ch 11", "Ch. 06: Circulation", "p. 75–81", "Priorities for cardiogenic, hypovolemic, and septic shock."),
    ("Basic Adult Healthcare", "Ch 17-20", "Ch. 09: Respiration", "p. 259, 371–373", "Care for pneumonia, asthma, and chronic obstructive pulmonary disease."),
    ("Basic Adult Healthcare", "Ch 21-25", "Ch. 06: Circulation", "p. 59, 65, 69", "Management of ACS, heart failure, and myocardial infarction."),
    ("Basic Adult Healthcare", "Ch 27", "Ch. 06: Circulation", "p. 67", "Monitoring for complications like stroke or heart failure."),
    ("Basic Adult Healthcare", "Ch 28", "Ch. 02: Next Gen Clinical Judgment", "p. 421", "Focuses on safe blood administration, pre-transfusion assessments, and monitoring for transfusion reactions."),
    ("Basic Adult Healthcare", "Ch 29", "Ch. 07: Protection", "p. 271, 275", "Management of iron deficiency and sickle cell crisis, focusing on perfusion and pain management."),
    ("Basic Adult Healthcare", "Ch 30", "Ch. 07: Protection", "p. 291, 297", "Nursing care for leukemia and multiple myeloma, specifically addressing infection prevention and bone pain."),
    ("Basic Adult Healthcare", "Ch 32", "Ch. 07: Protection", "p. 239", "Clinical mapping for HIV/AIDS, focusing on immune system collapse and opportunistic infections."),
    ("Basic Adult Healthcare", "Ch 33", "Ch. 07: Protection", "p. 235", "Recognition and emergency management of hypersensitivity reactions and anaphylaxis."),
    ("Basic Adult Healthcare", "Ch 34", "Ch. 15: Adaptation", "p. 241, 243", "Management of chronic autoimmune conditions like Lupus (SLE) and Rheumatoid Arthritis."),
    ("Basic Adult Healthcare", "Ch 36", "Ch. 13: Movement", "p. 173, 175", "Care for mobility issues related to osteoarthritis and osteoporosis."),
    ("Basic Adult Healthcare", "Ch 37", "Ch. 13: Movement", "p. 171", "Priorities for fracture management, including immobilization and neurovascular checks."),
    ("Basic Adult Healthcare", "Ch 40", "Ch. 11: Nutrition", "p. 359", "Priorities for Peptic Ulcer Disease, including H. pylori management and GI bleeding risks."),
    ("Basic Adult Healthcare", "Ch 41", "Ch. 11: Nutrition", "p. 321, 325", "Management of Crohn’s disease and intestinal obstructions."),
    ("Basic Adult Healthcare", "Ch 43", "Ch. 11: Nutrition", "p. 311, 313", "Clinical judgment for liver cirrhosis and the various types of viral hepatitis."),
    ("Basic Adult Healthcare", "Ch 45", "Ch. 12: Hormonal", "p. 317, 351", "Assessment of thyroid and adrenal gland dysfunctions (Addison's, Hyperthyroidism)."),
    ("Basic Adult Healthcare", "Ch 46", "Ch. 10: Regulation", "p. 335–341", "Comprehensive care for Type 1 and Type 2 diabetes, DKA, and HHNS."),
    ("Basic Adult Healthcare", "Ch 48", "Ch. 10: Regulation", "p. 361, 365", "Priorities for Acute Kidney Injury (AKI) and Chronic Kidney Disease (CKD)."),
    ("Basic Adult Healthcare", "Ch 58", "Ch. 13: Movement", "p. 201, 205", "Clinical judgment for cataracts and glaucoma, focusing on safety and sensory perception."),
    ("Basic Adult Healthcare", "Ch 61", "Ch. 17: Cognition", "p. 195, 303", "Care for patients with seizures and increased intracranial pressure."),
    ("Basic Adult Healthcare", "Ch 62", "Ch. 06: Circulation", "p. 53, 55", "Differentiating between ischemic (embolic) and hemorrhagic stroke interventions."),
    ("Basic Adult Healthcare", "Ch 65", "Ch. 13: Movement", "p. 191", "Nursing priorities for Parkinson’s disease, addressing mobility and safety."),
    ("Basic Adult Healthcare", "Ch 66", "Ch. 07: Protection", "p. 225, 261", "Focuses on influenza and tuberculosis transmission prevention and treatment."),
    ("Basic Adult Healthcare", "Ch 67", "Ch. 18: Multi-Concept", "p. 431", "Triage and injury prevention for trauma, bites, and environmental emergencies."),
    
    # --- Pharmacology ---
    ("Pharmacology", "Ch 4", "Ch. 02: Next Gen Clinical Judgment", "p. 437", "Guidelines for safe medication administration, rights of nursing, and error prevention."),
    ("Pharmacology", "Ch 5", "Ch. 02: Next Gen Clinical Judgment", "p. 3", "Success tips for mastering math conversions and clinical dosage logic."),
    ("Pharmacology", "Ch 9", "Ch. 07: Protection", "p. 231, 233", "Priorities for resistant infections like MRSA and VRE, focusing on infection control."),
    ("Pharmacology", "Ch 15", "Ch. 07: Protection", "p. 215", "Concept overview of immunity, inflammatory triggers, and protection nursing cues."),
    ("Pharmacology", "Ch 16", "Ch. 12: Hormonal", "p. 319", "Management of steroid therapy and monitoring for Cushing-like side effects."),
    ("Pharmacology", "Ch 18", "Ch. 04: Unfolding Concepts II", "p. 99", "Health promotion through immunizations and primary prevention strategies."),
    ("Pharmacology", "Ch 21", "Ch. 16: Emotion", "p. 135", "Assessing therapeutic effects and safety risks in patients with clinical depression."),
    ("Pharmacology", "Ch 23", "Ch. 13: Movement", "p. 195", "Monitoring seizure activity, types of seizures (tonic-clonic/absence), and safety cues."),
    ("Pharmacology", "Ch 24", "Ch. 13: Movement", "p. 191", "Focus on akinesis, rigidity, and the 'Ali Loves Boxing Matches' med mnemonic."),
    ("Pharmacology", "Ch 26", "Ch. 14: Comfort", "p. 111, 113", "Priorities for comfort and acute pain management, including respiratory monitoring."),
    ("Pharmacology", "Ch 35", "Ch. 12: Hormonal", "p. 347, 349", "Managing antidiuretic hormone imbalances and associated fluid volume cues."),
    ("Pharmacology", "Ch 36", "Ch. 12: Hormonal", "p. 317, 319", "Nursing care for cortisol imbalances (Addison's vs. Cushing's Syndrome)."),
    ("Pharmacology", "Ch 37", "Ch. 12: Hormonal", "p. 343, 351", "Assessing metabolic regulation, tremors, and temperature intolerance."),
    ("Pharmacology", "Ch 38", "Ch. 10: Regulation", "p. 335, 337", "Focus on the '3 P's' (polyuria, polydipsia, polyphagia) and hypoglycemia risks."),
    ("Pharmacology", "Ch 43", "Ch. 06: Circulation", "p. 67, 70", "Managing hypertension with the 'ABCD' treatment logic and monitoring for TIA."),
    ("Pharmacology", "Ch 44", "Ch. 06: Circulation", "p. 65, 68", "Managing HF using 'UNLOAD FAST' and monitoring for Digoxin toxicity (VANBAD)."),
    ("Pharmacology", "Ch 46", "Ch. 06: Circulation", "p. 59, 61", "Using 'MONAH' for acute coronary syndrome and managing atherosclerosis."),
    ("Pharmacology", "Ch 48", "Ch. 06: Circulation", "p. 51, 73", "Focus on DIC, DVT prevention, and pulmonary embolism (PE) risk factors."),
    ("Pharmacology", "Ch 49", "Ch. 07: Protection", "p. 271", "Priorities for iron deficiency and sickle cell anemia management."),
    ("Pharmacology", "Ch 51", "Ch. 08: Homeostasis", "p. 163", "Assessing fluid overload, edema, and effectiveness of loop vs. thiazide diuretics."),
    ("Pharmacology", "Ch 55", "Ch. 09: Respiration", "p. 371, 373", "Use of adrenergics and steroids to manage pink puffers (emphysema) vs. blue bloaters."),
    ("Pharmacology", "Ch 57", "Ch. 11: Nutrition", "p. 359", "Treatment for Peptic Ulcer Disease and H. pylori ('Please Make Tummy Better')."),
    ("Pharmacology", "Ch 58", "p. 321, 323", "Care for elimination abnormalities and colostomy/ileostomy procedures.")
]
